backend:
  name: github
  repo: Al-Rozhkov/arcon.gs

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "series"
    label: "Серии"
    extension: "json"
    folder: "products/series"
    path: "{{productCategory}}/{{slug}}"
    create: true
    slug: "{{id}}"
    fields:
      - {label: "Идентификатор", name: "id", widget: "string"}
      - {label: "Описание", name: "body", widget: "text"}
      - {label: "Раздел каталога", name: "productCategory", widget: "string"}
      - {label: "Покрытие", name: "coating", widget: "select", options: ["ng", "tan", "tin", "pp"]}
      - {label: "Хвостовик", name: "tail", widget: "select", options: ["cylinder", "weldon"]}
      