backend:
  name: github
  repo: Al-Rozhkov/arcon.gs
  squash_merges: true

media_folder: "static/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

collections:
  - name: "series"
    label: "Серии фрез"
    extension: "json"
    folder: "products/series/end-mills"
    path: "{{productCategory}}/{{slug}}"
    create: true
    slug: "{{id}}"
    identifier_field: id
    summary: "{{body}}"
    fields:
      - {label: "Идентификатор", name: "id", widget: "string"}
      - {label: "Описание", name: "body", widget: "text"}
      - {label: "Раздел каталога", name: "productCategory", widget: "string"}
      - label: "Основное применение"
        name: "mainUsage"
        widget: "select"
        multiple: true
        options: &usageOptions
          - {label: "Углеродистая и легированная сталь", value: "p"}
          - {label: "Чугун", value: "k"}
          - {label: "Нержавеющая сталь", value: "m"}
          - {label: "Закаленная сталь", value: "h"}
          - {label: "Закаленная сталь h1.1", value: "h1.1"}
          - {label: "Закаленная сталь h1.2", value: "h1.2"}
          - {label: "Цветные металлы", value: "n"}
          - {label: "Сплавы на основе алюминия", value: "n1"}
          - {label: "Сплавы на основе меди", value: "n3"}
          - {label: "Суперсплавы и титан (жаропрочные сплавы)", value: "s"}
      - label: "Возможное применение"
        name: "possibleUsage"
        widget: "select"
        required: false
        multiple: true
        options: *usageOptions
      - label: "Покрытие"
        name: "coating"
        widget: "select"
        required: false
        options:
          - {label: "nACo-G", value: "ng"}
          - {label: "TiAlN", value: "tan"}
          - {label: "TiN", value: "tin"}
          - {label: "PurePolish (полировка)", value: "pp"}
      - label: "Хвостовик"
        name: "tail"
        widget: "select"
        required: false
        options:
          - { label: "Цилиндрический", value: "cylinder" }
          - { label: "Weldon", value: "weldon" }
      - label: "Форма торца"
        name: "endShapes"
        widget: "select"
        required: false
        multiple: true
        options:
          - { label: "Торец без фаски, наостро", value: "rect-sharp" }
          - { label: "Торец с притуплением", value: "rect-r" }
          - { label: "Торец с фаской chх45˚", value: "rect-f" }
          - { label: "Радиусной торец", value: "radius" }
          - { label: "Сферический торец", value: "sphere" }
      